name: Jobs Chaining

on: 
  push:
    branches: 
      - main
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}"

  job_2:
    runs-on: ubuntu-latest
    needs: [job_1]
    steps:
      - run: "echo Job: ${{ github.job }}"

  job_3:
    runs-on: ubuntu-latest
    needs: job_2
    steps:
      - run: |
          echo "Job: ${{ github.job }}"

  job_4:
    runs-on: ubuntu-latest
    needs: job_3
    steps:
      - run: "echo Job: ${{ github.job }}"
        shell: bash
      
  job_5:
    runs-on: ubuntu-latest
    needs: job_4
    steps:
      - run: |
          print("Job: ${{github.job}}")
        shell: python
